// Mirrors sync/topics.py's CANONICAL_TOPICS. Keep these two lists in sync
// by hand — there's no shared module between the Python sync scripts and
// this Next.js app. Used by the admin question-topic editor's dropdown.
export const CANONICAL_TOPICS = [
  "Arrays & Strings",
  "Linked Lists",
  "Trees & Graphs",
  "Dynamic Programming",
  "Recursion & Backtracking",
  "Sorting & Searching",
  "Hashing",
  "Stacks & Queues",
  "Greedy Algorithms",
  "Bit Manipulation",
  "Math & Number Theory",
  "System Design",
  "Object-Oriented Design",
  "Databases & SQL",
  "Operating Systems",
  "Networking",
  "Distributed Systems",
  "JavaScript & TypeScript",
  "HTML & CSS",
  "React",
  "Node.js & Backend (MERN)",
  "Python",
  "Java & Spring",
  "Machine Learning, AI & Data Science",
  "DevOps & Cloud",
  "Testing & QA",
  "Security",
  "Excel",
  "CRM",
  "Behavioral",
  "Case Study & Product Thinking",
  "Aptitude & Guesstimates",
  "Uncategorized",
] as const;
